### ISSUE TITLE
Variable sithick not found

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1007]
**Describe the bug**
When running the `recipe_check_obs.yml`, the `PIOMAS/sithick` data is not found as reported in this [comment](https://github.com/ESMValGroup/ESMValTool/pull/1882#issuecomment-778072604). Even if the variable name is set to `sithick` in the recipe, the data cannot be found because the `data_finder` looks for the variable `sit`.
The filenames contain the variable name `sithick`:  OBS_PIOMAS_reanaly_2.1_day_sithick_197901-197912.nc

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/5996294/main_log_debug.txt)
[recipe_check_PIOMAS.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/5996303/recipe_check_PIOMAS.yml.txt)

@jvegasbsc any thoughts on that?

**Comment by jvegasbsc** [comment]
ESMValTool should be able to found it using both names, mainly because we don't want that users need to know which variables have seen their short names modified during CMIP history. I will take a look and fix it.

I agree with @bouweandela in that it will be better if PIOMAS uses CMIP5 name. I will also correct it

**Comment by bouweandela** [comment]
It looks like there may also be something weird going on with `sit` in CMIP5 and `sithick` in CMIP6. I wonder if this entry that they are the same is correct?
```
esmvalcore/cmor/variable_alt_names.yml:12:- ['sit', 'sithick']
```

The comment in the CMIP6 and OBS4MIPS table for the variable `sithick` says:
```
"Actual (floe) thickness of sea ice (NOT volume divided by grid area as was done in CMIP5)",
```
Moreover, there is custom `sithick` variable defined in esmvalcore/cmor/tables/custom/CMOR_sithick.dat, while `sit` is available in CMIP5 OImon, so why would we need that?

Do we any experts on this topic on the team?

**Comment by valeriupredoi** [comment]
I'd ping one of the scientists @ledm @alistairsellar @tillku

**Comment by alistairsellar** [comment]
I *used* to be a sea-ice expert, so happy to advise on the science aspects...

I'm not sure what the science question is though. It looks from the sithick description like CMIP6 requested a physically different variable from what was requested in CMIP5. You can map between the two easily if you have sea-ice concentration though.

**Comment by bouweandela** [comment]
Thanks, that's the answer we needed. At the moment the tool thinks these are identical, which is clearly not the case so we just need to remove line 12 from
```
esmvalcore/cmor/variable_alt_names.yml:12:- ['sit', 'sithick']
```
and then we can probably close this issue.

**Comment by alistairsellar** [comment]
That is certainly a solution to the inconsistency, but doesn't solve the original problem that sithick is not available for CMIP5. That problem could be solved by using sit / sic when sithick is not available.

**Comment by bouweandela** [comment]
I think that is solved by implementing `sithick` as a derived variable for CMIP5, so it can be computed: https://github.com/ESMValGroup/ESMValCore/blob/0c798617b885777a5ffa1697c39bb46974a73bab/esmvalcore/preprocessor/_derive/sithick.py#L39-L43

The problem here is that we have a table of variables that are identical but have different names in CMIP5 and CMIP6 (in the file esmvalcore/cmor/variable_alt_names.yml) and CMIP5 `sit` and CMIP6 `sithick` are listed as identical there, but apparently they are not identical, so they shoulnd't be in this table.

**Comment by alistairsellar** [comment]
Sounds good!

**Comment by jvegasbsc** [comment]
> I'm not sure what the science question is though. It looks from the sithick description like CMIP6 requested a physically different variable from what was requested in CMIP5. You can map between the two easily if you have sea-ice concentration though.

If I remmber correctly my discussions with David Docquier when developing this, by its definition sit should map to sivol but in reality in most CMIP5 models they were reporting sithick
