### ISSUE TITLE
Sample data multimodel stats tests failing locally

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1058]
```
________________________________ ERROR at setup of test_multimodel_no_vertical_dimension ________________________________
[gw1] linux -- Python 3.9.2 /home/valeriu/miniconda3py39/envs/esmvaltool-latest/bin/python3.9

request = <SubRequest 'timeseries_cubes_month' for <Function test_multimodel_regression_month[overlap]>>

    @pytest.fixture(scope="module")
    def timeseries_cubes_month(request):
        """Load representative timeseries data."""
        # cache the cubes to save about 30-60 seconds on repeat use
        cache_key = get_cache_key("sample_data/monthly")
        data = request.config.cache.get(cache_key, None)
    
        if data:
>           cubes = pickle.loads(data.encode('latin1'))
E           AttributeError: Can't get attribute 'BasicLayer' on <module 'dask.highlevelgraph' from '/home/valeriu/miniconda3py39/envs/esmvaltool-latest/lib/python3.9/site-packages/dask/highlevelgraph.py'>

tests/sample_data/multimodel_statistics/test_multimodel.py:87: AttributeError
```

all 10 tests failing locally on my machine. We've seen this sort of behavior previously, and we had to regenerate the MM cached nc files locally, and run again. This is showing the current implementation is rather brittle - @stefsmeets can we do something about this and avoid such fails? I am not bothered, but a user that's got limited experience may panic and lose their beans :beer:

**Comment by stefsmeets** [comment]
This is not really to do with the tests itself, but more how we cache the data to save about a minute on loading the sample data. This is a bit of a work-around to be able to use pytest`s caching mechanism, as I'd rather save and load the data using iris. But this also has issues, because saving and loading the data with iris does not result in the same object (`iris` adds/removes/fixes some metadata in this process).

So, `pickle` is used here to generate the exact same object in memory as before. The pickled object (`bytes`) is then decoded to a string object so we can use the pytest caching mechanism. It seems like it goes wrong with the pickling. Unfortunately, I cannot reproduce that on my machine, and I'm not sure where the dask thing comes from.

Do you know a better serialization format for iris cubes?

Alternatively, we can turn off the caching altogether, but that adds about a minute just for loading the sample data.

**Comment by bouweandela** [comment]
> I'm not sure where the dask thing comes from.

The cache was created with a different version of dask. We could add the dask version used to the cache key here:

https://github.com/ESMValGroup/ESMValCore/blob/c0cc45fde40e4b4f943cb47df262a6d183128a93/tests/sample_data/multimodel_statistics/test_multimodel.py#L64-L76

but I'm a bit worried this cache may be an endless source of trouble. So maybe this

> Alternatively, we can turn off the caching altogether, but that adds about a minute just for loading the sample data.

would be a better idea.

> Do you know a better serialization format for iris cubes?

The best available serialization format for iris cubes is NetCDF, because iris is built around the [CF conventions](https://cfconventions.org/), which are closely related to the NEtCDF file format: "The conventions for CF (Climate and Forecast) metadata are designed to promote the processing and sharing of files created with the NetCDF API. "

**Comment by valeriupredoi** [comment]
@bouweandela ditto! Sorry, Stef, wanted to reply on this on Fri, but it slipped through the cracks, totally agree with Bouwe on this :+1:

**Comment by stefsmeets** [comment]
If this is the case, did `pytest --cache-clear` not solve the issue?

The other question I have is, why is this now dependent on dask all of a sudden?

**Comment by valeriupredoi** [comment]
I didn't run that and we should probably not expect a Regular Joe/Jane user to know how to run that. About dask, I suspect it's linked from iris

**Comment by stefsmeets** [comment]
As far as I can tell, none of the esmvalcore developers are regular joe's/jane's 😅 
Maybe we can improve the error message there, or revert to loading the data 'the normal way' if loading from cache fails.

**Comment by valeriupredoi** [comment]
yes, I like those both :grin:

**Comment by valeriupredoi** [comment]
no idea why I've not closed this before, but I've not seen these tests fail in a long time, all good :cactus:
