### ISSUE TITLE
Automatic area weights calculation for rotated pole grids is incorrect in some cases

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1084]
**Describe the bug**
The automatic calculation of cell areas in rotated grids

https://github.com/ESMValGroup/ESMValCore/blob/622366123bc57df1796a558dec7b24316c113041/esmvalcore/preprocessor/_area.py#L253-L261

that was implemented for CORDEX in #631 gives partly wrong results for CMIP5 data (potentially for other datasets as well).

For example, consider `areacello_fx_GFDL-ESM2G_historical_r0i0p0.nc`:

![areacello](https://user-images.githubusercontent.com/32543114/116108473-36e16f80-a6b4-11eb-8109-f9d387d437af.png)
![core](https://user-images.githubusercontent.com/32543114/116108482-38129c80-a6b4-11eb-8513-7bedc54dde5d.png)

You can see that north of 65°N the cell areas calculated by ESMValCore deviate quite a lot from the true cell areas of the model. This is not surprising, since there is a comment in the model's `areacello` that says `The North Pole singularity is avoided by using this nonregular grid north of 65N.`.

There are two possibilities here:

1. This is an issue of the specific model (GFDL-ESM2G) and the calculation given by the code above is in general correct.
2. It is not possible to generalize the calculation of the cell areas in rotated pole grids and CORDEX is a special case where it is possible.

Maybe @zklaus can shed some light on this? If option 2. is true than this piece of code needs to be removed as it might lead to wrong results without any errors/warnings. As an alternative, the cell areas can be specified with the optional argument `fx_variables`. If these are available for CORDEX, these should be used.

**Comment by zklaus** [comment]
Just had a look. The issue is fairly common, but still an error on the side of the model.

The coordinates that the model uses are **not** rotated pole coordinates. They use a tripolar grid.
The confusion arises because for the 1d dim coord they use `grid_latitude` and `grid_longitude`, which sounds like a generic coordinate for exactly this purpose, but is in fact defined much more narrowly as rotated pole coordinates.

So the calculation for rotated pole coordinates can be generalized; the model is at fault for claiming that it is using rotated pole coordinates when it is not.

The best way to deal with this in terms of fixes is to remove the `rlat` and `rlon` coordinates, possibly replacing them with simple index coordinates.

**Comment by zklaus** [comment]
Btw, this is the exact same problem we see with the BCC models.

**Comment by schlunma** [comment]
Alright, that makes sense. Thanks for the clarification!
