### ISSUE TITLE
Coding sprint on native model data

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1119]
We will do a virtual coding sprint on native model data on 2021-05-11, 14:00 CEST. If you want to participate, please get in touch.

@senesis, I hope you got my email. If not, please accept my apologies and get in touch here. We will have a second session tomorrow afternoon at 14:00 CEST.

**Comment by senesis** [comment]
@zklaus , I did not get your email. I wont't be available from 14:15 to 15:00, but I would like to join at 14:00, for the introductory part.
I can also attend tomorrow afternoon

**Comment by senesis** [comment]
@zklaus and I did not get any connection detail

**Comment by senesis** [comment]
senesi

posteo.net

**Comment by zklaus** [comment]
Thanks, just send you an email. Let me know if it didn't work.

**Comment by senesis** [comment]
@zklaus , @bouweandela (cc: @senesis)

Beyond what has been discussed, it would be useful to be able to specify the DRS also at the dataset level. This because :
- IPSL would like to use two DRS at the same time when processing two of its simulations (one DRS for each simulation), and 
- if one has to use 2 projects for using 2 DRS,  one must define 2 directories in cmor/_fixes, even if fix code is the same for the two projects (which is actually the case)

I recognize this would require multiple changes in _data_finder.
Let me know if it is worth creating an issue

**Comment by senesis** [comment]
@zklaus , @bouweandela 

When activating the mapping, some dataset attributes are carried along to the provenance handler, and then can generate an error, as shown below.

I traced that back to the fact that run file `preproc/map/tas/metadata.yml` includes a line :

>   igcm_dir:ATM: null

which as a syntax error; but I am not able to figure ut where it comes from, and when trying to remove this igcm_dir key from my settings, the error appears to be sticky from one run to next one)

Any help would be welcome



> File "/home/ssenesi/EVT/ESMValCore/esmvalcore/_task.py", line 626, in _collect_provenance
>     product.save_provenance()
>   File "/home/ssenesi/EVT/ESMValCore/esmvalcore/_provenance.py", line 252, in save_provenance
>     self._include_provenance()
>   File "/home/ssenesi/EVT/ESMValCore/esmvalcore/_provenance.py", line 236, in _include_provenance
>     attributes = self._select_for_include()
>   File "/home/ssenesi/EVT/ESMValCore/esmvalcore/_provenance.py", line 208, in _select_for_include
>     'provenance': self.provenance.serialize(format='xml'),
>   File "/data/ssenesi/conda/esmvaltool-dev/lib/python3.9/site-packages/prov/model.py", line 2479, in serialize
>     serializer.serialize(stream, **args)
>   File "/data/ssenesi/conda/esmvaltool-dev/lib/python3.9/site-packages/prov/serializers/provxml.py", line 52, in serialize
>     xml_root = self.serialize_bundle(bundle=self.document, force_types=force_types)
>   File "/data/ssenesi/conda/esmvaltool-dev/lib/python3.9/site-packages/prov/serializers/provxml.py", line 132, in serialize_bundle
>     subelem = etree.SubElement(
>   File "src/lxml/etree.pyx", line 3136, in lxml.etree.SubElement
>   File "src/lxml/apihelpers.pxi", line 179, in lxml.etree._makeSubElement
>   File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
> ValueError: Invalid tag name 'igcm_dir:ATM

`

**Comment by senesis** [comment]
@zklaus , @bouweandela 
Additionally, being able to set the DRS at the dataset level would allow to use `native6` project rather than define one (or two) specific projects. It would spare on entries in the `_fixes` directory. But this would mean that mapping files in `_config/mappings` should be searched using both project's and dataset's values (so, like fixes)

**Comment by bouweandela** [comment]
>  it would be useful to be able to specify the DRS also at the dataset level. 
>  Let me know if it is worth creating an issue

Please have a look at #494

**Comment by zklaus** [comment]
Let's take up the drs issue in #494.

I'll close this issue now. The sprint has taken place and more actions came out of it.
