### ISSUE TITLE
plots not (fully) generated after recipe run 

### ISSUE THREAD

**Issue by Emmadd** [ESMValGroup/ESMValCore#1126]
I'm fairly new to using ESMValTool so forgive me if this is a silly issue.

I am running a variation to an example recipe, for generation climate scenarios. I am in the first step, global matching and seem to have managed to read in a bunch of data. However, I get an error message after the calculations in the plotting procedure (I am not familiar with pydot). This is the error information:

 File "/home/emmad/miniconda3/envs/KCS/lib/python3.9/site-packages/pydot.py", line 1956, in create
    assert process.returncode == 0, (
AssertionError: "dot" with args ['-Tsvg', '/tmp/tmpt1qo24om'] returned code: 1
stdout, stderr:
 b''
b'Error: /tmp/tmpt1qo24om: syntax error in line 204 scanning a HTML string (missing \'>\'? bad nesting? longer than 16384?)\nString starting:<<TABLE cellpadding="0" border="0">\n    <TR>\n        <TD align="left" href="https\n'

The figure global_matching.png is saved but compared to an earlier version two red dots are missing.

I am attaching my recipe (as txt, yml is not accepted) and log file. I run esmvaltool with the following command:
esmvaltool run 01_recipe_test.yml --config_file=config.yml --diagnostics=global_matching

[01_recipe_test.txt](https://github.com/ESMValGroup/ESMValCore/files/6467116/01_recipe_test.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/6467117/main_log_debug.txt)

Thanks a lot! Emma

**Comment by bouweandela** [comment]
Do you still have the file `/tmp/tmpt1qo24om` mentioned in the error message? It looks like there is a problem with plotting the provenance (not the figures), because a strange character is encountered in it on line 204 of the file mentioned in the error message. This could have various reasons, but it would really help to see the character and it's context.

**Comment by Emmadd** [comment]
It was a bit hard to get the tmp-file because it is removed during the run, even when the error is encountered. But I managed to save it (running a continuous while; copy loop). Here's the file and the corresponding error message: 
"dot" with args ['-Tsvg', '/tmp/tmptdfy6thm'] returned code: 1
stdout, stderr:
 b''
b'Error: /tmp/tmptdfy6thm: syntax error in line 585 scanning a HTML string (missing \'>\'? bad nesting? longer than 16384?)\nString starting:<<TABLE cellpadding="0" border="0">\n    <TR>\n        <TD align="left" href="https\n'

Line 585 has a long list of EC-Earth model data that I think was merged into the file I use. 

Thanks for your help!
[tmptdfy6thm.txt](https://github.com/ESMValGroup/ESMValCore/files/6492010/tmptdfy6thm.txt)

**Comment by Emmadd** [comment]
perhaps pydot could spread things over multiple lines if they are too long? I am not familiar with pydot...

**Comment by bouweandela** [comment]
It looks like the line is indeed too long, is this list of files a global attribute of the input netcdf file?

For now, the easiest workaround would probably be to comment out the line that plots of the provenance. If you open the
file "/home/emmad/miniconda3/envs/KCS/lib/python3.9/site-packages/esmvalcore/_provenance.py", go to line 261, and put a `#` in front of the code `figure.write_svg(filename + '.svg')`, the tool will run as expected. You'll miss the plots of the [provenance](https://docs.esmvaltool.org/en/latest/community/diagnostic.html#recording-provenance), but that shouldn't be a problem.

Maybe we should get rid of those provenance plots altogether if they're causing problems, because they are hardly human readable anyway.

**Comment by Emmadd** [comment]
The list is a list of files that was merged to create te file I am using, which is indeed stored as an attribute of the input NetCDF file. (Not sure about the global part).

I've commented out the line that plots the provenance (and hope to have fixed the fixes that were leading to problems in my case). I think It'll work fine now.

Thanks for your help!
