### ISSUE TITLE
Support OpenDAP access to ESGF

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1131]
For downloading smaller subsets of data, it might be convenient to support the use of OpenDAP to access the data. See this [example](https://esgf-pyclient.readthedocs.io/en/latest/notebooks/demo/subset-cmip6.html) (note that iris also supports OpenDAP, there is no need to use xarray).

**Comment by bouweandela** [comment]
We could use esgf-pyclient to obtain the OpenDAP URLs, or obtain them from an intake-esm catalog if that exists somewhere.

**Comment by zklaus** [comment]
Just came off a call with @philipkershaw. It really seems that OPeNDAP is on its way out of ESGF. This is for a number of technical reasons they experienced in testing more advanced OPeNDAP features such as subsetting, where it is just rather slow. Also the default way of serving files is now Nginx instead of Thredds, again for performance reasons, and if you wanted to use OPeNDAP, you would have to keep your Thredds server, which is possible, but will no longer be supported upstream.

Instead, attention turns more and more to object stores and zarr. So if we are trying to decide on where to invest, I'd say those are more promising candidates.

**Comment by bouweandela** [comment]
Do you have any idea what timescale we're talking about here? My plan was to support both in v2.4.

Do you know if there is or will be some unified way to find out the location of these zarr arrays? I've found some intake catalogs (see #31), but nothing like `esgf-python`.

**Comment by zklaus** [comment]
I am not aware of a concrete timeline, but let me split this up into two parts: Phasing out OPeNDAP and providing Zarr et al. Imho, phasing out OPeNDAP has already started since a default installation of an ESGF node will not provide OPeNDAP serving. New technologies are at an advanced experimentation stage at the moment, where there is already some commitment to some particular underlying technology (see https://github.com/cedadev/cmip6-object-store/, https://help.jasmin.ac.uk/article/4847-using-the-jasmin-object-store), but no full integration into ESGF. When this comes, I expect to get Zarr URLs directly from ESGF.

**Comment by zklaus** [comment]
At least the second part will probably not be in place for 2.4.0; what has a higher chance of being in place by then is a WPS based solution, which is being developed within IS-ENES right now. Alessandro Spinuso from KNMI knows more about this.

**Comment by zklaus** [comment]
Hm. I still think that OPeNDAP is on its way out of ESGF, but I wonder if that even matters so much or if we should just rename the issue. At the end of the day, if we have a URL in the cube that allows us to download only parts of the data from a remote location, we may not need to care whether that is happening via OPeNDAP, or zarr, or whathaveyou, right? So in this sense it would be only about getting the right resource locator into the cube and making sure that iris can handle it.

In any case, given the time constraints, this will not make it into 2.4.0. @bouweandela, how do you want to proceed?

**Comment by bouweandela** [comment]
Let's leave the issue open for now. My impression is that OpenDAP will still be around for a few more years, while zarr is still in an experimental phase. So for now it might still make sense to add support for OpenDAP if it's not too much work, but I have no time to do that before the v2.4 release and other issues might be more important.
