### ISSUE TITLE
Preprocessor feature request: Common mask for multiple datasets

### ISSUE THREAD

**Issue by BenMGeo** [ESMValGroup/ESMValCore#116]
For multiple datasets it is necessary to produce a common mask and apply it to all of them if you want to compare respective results. 

As far as I know, there is currently no preprocessor for producing and applying such a common mask.

Is there a work-around? Is this a needed/wanted feature? If I'm the only one, I can focus on doing this in the diagnostic.

**Comment by BenMGeo** [comment]
I had an offline discussion with @axel-lauer and he pointed me to the threshold functionlaity.

```
mask_fillvalues:
        threshold_fraction: 0.0
```

This does the trick, but seems rather counter-intuitive, in my eyes.

Do we want to have a wrapper here?

**Comment by bouweandela** [comment]
I would prefer better documentation over a wrapper.

**Comment by BenMGeo** [comment]
Besides, is there any need for a dataset based threshold functionality? One might think about splitting the current combined version into 2 seperate steps?

**Comment by valeriupredoi** [comment]
I just finished writing the documentation for the preprocessor (including `mask_fillvalues`) have a look at https://github.com/ESMValGroup/ESMValCore/pull/113

you can throttle the `threshold_fraction` indeed and that will combine the masks into one cumulative one, cheers for raising the issue since I can include a ProTip to the documentation.

From a functional point of view the fillvalues mask was one of the first preprocessor we implemented, and is rather important, combining masks without filling is of course a special case of it and I don't think there is a need for yet another masking operation since this one does it a-ok :beer:

**Comment by valeriupredoi** [comment]
also, the threshold is important for filling the missing values, `mask_fillvalues` is something that @mattiarighi bought me a beer for implementing, so it's solid :grin:

**Comment by valeriupredoi** [comment]
just added a note in #113 to the `preprocessor` documentation documenting this, cheers @BenMGeo :beer:

**Comment by valeriupredoi** [comment]
can we close this then?

**Comment by BenMGeo** [comment]
If it's just me, who thinks it's an odd way to do/call it, I'm fine with leaving it and closing. I'm having a look at #113 right now.

Thanks @valeriupredoi for implementing it.

**Comment by BenMGeo** [comment]
Solved via #113.
