### ISSUE TITLE
How should multi-model statistics work for a single cube?

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1211]
The new multi-model statistics code refuses to calculate statistics on a single model.
That is one approach to things, but for most statistics it's perfectly possible to compute them on a single cube as well, albeit perhaps not super useful.

To me, it seems the two alternatives here are
- Refuse computation on a single cube
- Compute according to the following table that lists all supported statistics

|Statistic|Result|
|---------|------|
|mean|input|
|median|input|
|max|input|
|min|input|
|std| 0 (zero)|
|pXX.YY| ???|

What do you prefer, @ESMValGroup/esmvaltool-developmentteam ?

**Comment by stefsmeets** [comment]
The output for `pXX.YY` should also be the input.

**Comment by bouweandela** [comment]
I would prefer a refusal to compute, because trying to compute a multimodel statistic on a single model probably means that there is a mistake in the recipe.

**Comment by zklaus** [comment]
I also think refusing to compute makes sense. @remi-kazeroni, @katjaweigel I think you guys stumbled over this recently. What do you think?

**Comment by zklaus** [comment]
There seem to be no opposing views, so we'll keep the current behavior.

**Comment by schlunma** [comment]
I'd like to re-open this discussion. I think multi-model statistics **should** work for single cubes. My main arguments are:

- This behavior is super counterintuitive since basically every other serious python library allows calculating statistics over a single element, e.g., `np.mean([1.0]) = 1.0`, `np.std([1.0]) = 0.0`, `da.arange(1.0).mean().compute() = 0.0`, or `pd.DataFrame({'a': [1]}).mean() = a    1.0`.
- With the introduction of [ensemble_statistics](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=ensemble_statistics#ensemble-statistics) and the fact that many models only provide one ensemble member you can quickly run into the `Cannot perform multicube statistics for a single cube.` issue when using this preprocessor. This can be resolved by using multiple preprocessors, but this unreasonably complicates the recipe and is really frustrating.

**Comment by schlunma** [comment]
@ESMValGroup/esmvaltool-coreteam any opinions on that?

**Comment by axel-lauer** [comment]
I agree with that. From a user perspective, it would be great if the multi-model statistics could handle single elements.

**Comment by schlunma** [comment]
I just realized that I already opened another issue for that back in February since I didn't search for closed issues :smile: 

https://github.com/ESMValGroup/ESMValCore/issues/1469

I will close that one and continue the discussion here.

**Comment by bouweandela** [comment]
> With the introduction of [ensemble_statistics](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html?highlight=ensemble_statistics#ensemble-statistics) and the fact that many models only provide one ensemble member you can quickly run into the Cannot perform multicube statistics for a single cube. issue when using this preprocessor.

That sounds like a good argument to allow it for ensemble_statistics.

**Comment by schlunma** [comment]
Yes, but since `ensemble_statistics` basically only calls `multi_model_statistics` internally, it would be much easier to allow it for `multi_model_statistics` and get `ensemble_statistics` for free.

https://github.com/ESMValGroup/ESMValCore/blob/96419a7e8d3321e7d07b33f390b924ebced8e102/esmvalcore/preprocessor/_multimodel.py#L522-L566

**Comment by dhohn** [comment]
Is all that babysitting necessary? A set with one member is well defined as are the summary statistics for it. IMHO there should at most be a warning that a trivial operation is conducted if that at all and be done with it.

**Comment by schlunma** [comment]
I kinda disagree here. From a mathematical point of view, most of these operations are well-defined for single cubes. For example, the arithmetic mean

$$
\bar{x} = \sum_{n=1}^{N} x_n
$$

makes perfectly sense for $N=1$. Why should we not allow it? As I mentioned above, basically all other Python packages allow that.

**Comment by schlunma** [comment]
> Is all that babysitting necessary? A set with one member is well defined as are the summary statistics for it. IMHO there should at most be a warning that a trivial operation is conducted if that at all and be done with it.

Yes, fully agree here!

**Comment by valeriupredoi** [comment]
@schlunma @dhohn et al - my apologies, I forgot to mention here that I had an inner monologue and I too agree we should be fine with N = 1 without any bells and whistles/red flags etc - am gonna go review Manu's PR so we can have it in 2.8 release :+1:

**Comment by schlunma** [comment]
Perfect, thanks V!! :beers:
