### ISSUE TITLE
output of era5 cmorizer recipe run on different years can not be used together in recipe

### ISSUE THREAD

**Issue by sverhoeven** [ESMValGroup/ESMValCore#1223]
I tried to run the `hydrology/recipe_pcrglobwb.yml` on 1990+1991, but failed with
```
iris.exceptions.ConcatenateError: failed to concatenate into a single cube.
  Cube metadata differs for phenomenon: air_temperature
```
in [log.txt](https://github.com/eWaterCycle/ewatercycle/files/6806715/log.txt), also see [main_log_debug.txt](https://github.com/eWaterCycle/ewatercycle/files/6806720/main_log_debug.txt)
I used ESMValCore v2.2.0 and ESMValTool v2.2.0

The `OBS6_ERA5_reanaly_1_day_tas_1991-1991.nc` file was generated last year and to fix [ERA5 CDS: Data corruption](https://confluence.ecmwf.int/display/CKB/ERA5+CDS:+Data+corruption#ERA5CDS:Datacorruption-Listofcorruptedfields) the `OBS6_ERA5_reanaly_1_day_tas_19900101-19901231.nc` file was regenerated this year.
This caused the difference in the metadata  between `OBS6_ERA5_reanaly_1_day_tas_1991-1991.nc` and `OBS6_ERA5_reanaly_1_day_tas_19900101-19901231.nc` as follows (using `ncdump -h`)
```diff
1c1
< netcdf OBS6_ERA5_reanaly_1_day_tas_1991-1991 {
---
> netcdf OBS6_ERA5_reanaly_1_day_tas_19900101-19901231 {
44c44
< 		:comment = "Contains modified Copernicus Climate Change Service Information 2020" ;
---
> 		:comment = "Contains modified Copernicus Climate Change Service Information 2021" ;
```

I think it is because of the `esmvaltool run cmorizers/recipe_era5.yml` command that inserts a comment with current year into the output files see
https://github.com/ESMValGroup/ESMValCore/blob/197a9a16d9feec3ba3c168eb9845ad8ceeb102aa/esmvalcore/cmor/_fixes/native6/era5.py#L381-L384

Can the comment be ignored during concatenation or can a comment be written without year in it? Or should I do something else?

**Comment by zklaus** [comment]
@Peter9192, @bouweandela, could you please have a look at this?

**Comment by Peter9192** [comment]
I can confirm the issue is with `iris.cube.CubeList.concatenate_cube()` not liking that comment. 

We discussed whether this note should be added [here](https://github.com/ESMValGroup/ESMValCore/pull/358#pullrequestreview-348975745). We can consider removing the timestamp, but actually I think it's good practice to store that sort of information in the cube metadata. On the other hand, I'd say ESMValTool should be able to deal with these minor differences in cube metadata. So we can:

- migrate issue to ESMValTool and implement a workaround in `diag_scripts/hydrology/pcrglobwb.py`
- open issue in iris to see if they'd be willing to make their checks a bit more lenient still, or asking how they suggest to deal with these kind of conflicts

**Comment by zklaus** [comment]
I think there are three global attributes that commonly cause this kind of problem:
- `creation_date`
- `history`
- `tracking_id`
- `comment`

Note that this is no coincidence: `history` and `comment` come directly from [the CF conventions](http://cfconventions.org/cf-conventions/cf-conventions.html#description-of-file-contents), while `creation_date` and `tracking_id` come from [CMIP](http://goo.gl/v1drZl).

To deal with this, we simply delete three of those four in https://github.com/ESMValGroup/ESMValCore/blob/2a0bb11cb52df3ec4a485a16bf92356e04617b52/esmvalcore/preprocessor/_io.py#L92. Perhaps we should just add `comment` to the list?

**Comment by Peter9192** [comment]
> Perhaps we should just add `comment` to the list?

That makes a lot of sense to me 👍

**Comment by zklaus** [comment]
@Peter9192, would you mind putting a PR together for this?

**Comment by bouweandela** [comment]
I'm not sure if adding `comment` is really the way to go here, there can be an endless variety of netcdf attributes that are not equal on all input files. That's why we've designed the [`esmvalcore.preprocessor.concatenate`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.concatenate) function such that it is able to deal with them. We remove attributes that we know would lose their meaning (such as a tracking ID) after processing with ESMValCore, the rest is concatenated by value here:
https://github.com/ESMValGroup/ESMValCore/blob/869d59761a23b44ff50faa92230a37f06d572a41/esmvalcore/preprocessor/_io.py#L129

A more robust solution to the problem would therefore be to use `esmvalcore.preprocessor.concatenate` instead of `iris.cube.CubeList.concatenate_cube()` in the diagnostic script.
