### ISSUE TITLE
Codecov doesn't work as expected

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1234]
codecov runs once then comments (attaching the graph) for the first commit then keeps reporting the same issue (if one is found), if the issue is fixed and the coverage is actually increased via subsequent commits, it still reports the same first issue and fails to regenerate both the comment with updated graph and not to fail - see https://github.com/ESMValGroup/ESMValCore/pull/1233 - I fixed the codecov.yml file so we don't have the codecov as failed test (we don't want a failure perse but rather as information) and I asked codecov to post a comment only if the coverage changes, but this last directive doesn't really work since it still shows the result from the very first commit.

**Comment by bouweandela** [comment]
Discussion on this issue is now taking place in #1241.

> if the issue is fixed and the coverage is actually increased via subsequent commits, it still reports the same first issue and fails to regenerate both the comment with updated graph and not to fail 

I think the comment is correctly updated https://github.com/ESMValGroup/ESMValCore/pull/1233#issuecomment-881369091, but this didn't happen if the unit tests failed because previously no coverage got uploaded to codecov in that case. Does that make sense?

**Comment by valeriupredoi** [comment]
could be, I made the upload happen `always` so it should be fine now (hopefully?)

**Comment by bouweandela** [comment]
Yes, I think so.

**Comment by bouweandela** [comment]
It's still not working if the tests fail, I found more problems with uploading test coverage for failed tests:
1) curl doesn't get installed because that step is not skipped. This is easily solved by adding a `when: always` to that step too
2) because we run two pytest commands, the second pytest command will not be executed if there is a problem with the first one, so this will lead to a dramatically reduced coverage
3) even when you fix 1) as I did in #1217, test coverage is still not uploaded for failing tests

**Comment by valeriupredoi** [comment]
> Maybe it's just not worth the trouble to try to get coverage results to work if the tests are failing. You need to fix those anyway before requesting a review.

agreed! or rerun if it's some fluke error during the tests run. Shall we bin this then?

**Comment by valeriupredoi** [comment]
binning this then
