### ISSUE TITLE
Installing an older version of ESMValCore (v2.1.0)

### ISSUE THREAD

**Issue by hahsan1** [ESMValGroup/ESMValCore#1258]
I wasn't able to find instructions for installing an older version of ESMValCore. I would like to install v2.1.0.

We tried running `conda install -c esmvalgroup -c conda-forge esmvalcore==2.1.0`, but that didn't seem to work, since `conda list` still shows the current installed version of esmvalcore (v2.2.0)

**Comment by zklaus** [comment]
Thanks for your interest, @hahsan1!  Could you tell us what went wrong? Was there any output from the `conda install` command?

**Comment by valeriupredoi** [comment]
hello @hahsan1 cheers for opening an issue with us! Here's what worked for me:
```
conda create -n esmvalcore210
conda activate esmvalcore210
conda install -c esmvalgroup -c conda-forge esmvalcore==2.1.0
(esmvalcore210) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list esmvalcore
# packages in environment at /home/valeriu/miniconda3/envs/esmvalcore210:
#
# Name                    Version                   Build  Channel
esmvalcore                2.1.0                      py_0    esmvalgroup
```
it#s always advisable to first create an empty environment where you will be installing the desired package from conda. You nay also want to try mamba instead of conda, but before doing that, as @zklaus pointed out, let's first try understand what went wrong with your installation -> could you please post the output of your command? Also, may I ask why you need an older version of the package? All our releases (up to the future 2.4) are backwards compatible so unless you need to use an older `iris` there's not much reason to use an older `esmvalcore`

**Comment by hahsan1** [comment]
Thank you @valeriupredoi we were able to install the specific version of esmvalcore after deleting and then making a new conda version. 

However, my colleague @hsuchyta was not able to install esmvaltool v2.1.1. We tried `conda create --name esmvaltool -c esmvalgroup -c conda-forge esmvaltool==2.1.1` but he was having some issues. So he will make a post on the ESMValTool page to explain that in more detail.

The reason we are using an older version is because it's the version I have installed and works with model input files and recipes I developed. When he tried running the same recipe on the newer version of ESMValTool, he got some CMOR check errors. So I'm thinking the newer version has more stringent checks. For now we just want to use the older version that works without issue, and perhaps in the future we will move to the newer version and tackle the issues we get.
