### ISSUE TITLE
Pin `numpy>=1.20`: `numpy=1.20` has a change in its C API that may trigger a backwards incompatibility error

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1272]
I'm back, with technical gubbins!

[Error seen and asked about here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) - third answer is the relevant one - this may bite us more frequently than we think since e.g Core may be installed from conda and built with a `numpy<1.20` and then when one installs a new dependency in their conda developemnt environment, conda will automatically update the resident (run) `numpy` to `numpy>=1.20`, then when the user tries running, proverbial stuff hits the fan. There are other scenarios that may lead to this issue, and I suspect they're prone to this especially if Python is old, like 3.7. I suggest we pin `numpy>=1.20` across Core and Tool - do we have any reason why not? Can't think of any myself...

**Comment by bouweandela** [comment]
Maybe if people would want to use other libraries in the same environment as esmvaltool that do not support numpy 1.20?

The alternative solution in the stack overflow answer might be a bit less restrictive:
> use minmum supported numpy version in pyproject.toml (`oldest-supported-numpy`)

But if you think that doesn't work for us, I would be fine with just using the latest numpy versions.

**Comment by valeriupredoi** [comment]
good point, Bouwe! My train of thoughts would be let's first go with the pin and see if there are any requests for use of `numpy<1.20` (bet you my boots there aren't since we've been building/installing with it for a few months now, and nobody said nothing) - plus, a pin always helps with a faster env solving :grin:

**Comment by zklaus** [comment]
I don't think this is an issue for us, here's why: The problem described in the linked Stackoverflow question happens when the numpy version in the build environment, particularly during the build of something that uses the C API of numpy, is different from the numpy version in the runtime environment.

This should be a complete non-issue for us if we have no c-extensions of our own. We don't, right?

So I think this is no reason for us to introduce pinning. Note that [numpy is a bit special in conda-forge](https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy), so if and when we need to pin it, we should have an extra close look.
