### ISSUE TITLE
Automatic download fails in rare cases

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1440]
In a recent discussion with @bettina-gier we noticed that the automatic download would sometimes fail with the following cryptic error message. I also remember that @axel-lauer had some problems with the automatic download feature, maybe that was also related to that.

```
...
File "/mnt/lustre02/work/bd0854/b309141/repos/ESMValCore/esmvalcore/esgf/_download.py", line 113, in get_preferred_hosts
    median_speed = median(speeds[h][SPEED] for h in speeds
  File "/mnt/lustre02/work/bd0854/b309141/mambaforge/envs/esm/lib/python3.10/statistics.py", line 452, in median
    raise StatisticsError("no median for empty data")
```

## How to reproduce

After a while we figured out that deleting the cache file `~/.esmvaltool/cache/esgf-hosts.yml` solves this issue. After digging into the code I found the reason for this. It is a result of a very unfortunate combination of an offline node with using a specific setting in `~/.esmvaltool/esgf-pyclient.yml`. On mistral, it can be reproduced with the following steps:

1. Delete `~/.esmvaltool/cache`.
2. Use this simple `~/.esmvaltool/esgf-pyclient.yml` with only two lines:
```
search_connection:
  url: "http://esgf-data.dkrz.de/esg-search"
```
3. Run a recipe where at least one dataset needs to be downloaded on a node which does not have an internet connection (e.g., `compute`). This will lead to the cryptic error above.
4. Even worse, now every subsequent run of the automatic download feature of a recipe with missing data will result in the same error  regardless if the node has an internet connection or not. This can only be solved by deleting the cache file.

## Explanation

Even though the node doesn't have an internet connection, it still can connect to the (local) ESGF node `http://esgf-data.dkrz.de/esg-search` to search for files. However, downloading files will not work, which will in turn fill the cache file `~/.esmvaltool/cache` with entries that read `speed (MB/s): 0`, e.g.

```
aims3.llnl.gov:
  duration (s): 0
  error: true
  size (bytes): 0
  speed (MB/s): 0
...followed by many other nodes
```

Finally, the following line will then output the error above, since no node with a non-zero entry is found:

https://github.com/ESMValGroup/ESMValCore/blob/2d3df9d923de3adf10739c90ab0372235b55b4ae/esmvalcore/esgf/_download.py#L113-L114

## Solution

This can be easily fixed by assigning `median_speed = 0.0` if no non-zero element is found. On nodes with no internet connection, this will lead to simply-to-interpret `Connection refused` errors. On nodes with a working internet connection, this will avoid this error here and later [fill the cached with reasonable entries](https://github.com/ESMValGroup/ESMValCore/blob/2d3df9d923de3adf10739c90ab0372235b55b4ae/esmvalcore/esgf/_download.py#L58-L73) that can be used in subsequent runs.

**Comment by valeriupredoi** [comment]
so the root cause is that the node has no internets, but the fallout is the malformed cache that persists and tells the downloader there is no internets, hence it goes to mamma crying right? I think the best solution is to have a connection test before any download is attempted eg:
```python
url = "http://www.google.com"  # have a site that's up (most) all the time
timeout = 5
try:
    request = requests.get(url, timeout=timeout)
except (requests.ConnectionError, requests.Timeout) as exception:
    print("No internets")
```

we check with a ping too, and set the ping timeout to a limit `import ping, socket / try: delay = ping.Ping('www.wikipedia.org', timeout=2000).do(); except socket.error, err: print err`

**Comment by schlunma** [comment]
I don't think that's necessary to be honest, the root cause here is that in that special case the search works (since the node CAN connect to the local ESGF node to search but cannot download from any node) which leads to the malformed cache. If any other node is used for the search that's totally fine (i.e., it results in an `Connection refused` error immediately).

With the easy fix I propose here (#1442) the user might have to wait a little bit longer, but then gets an error about the missing internet connection and then (hopefully) won't run into the same problem in the future.

**Comment by remi-kazeroni** [comment]
Thanks for the investigation @schlunma! I also had issues with the malformed cache but not exactly this one. Deleting the cached results always helped. This is written at the end of the ESGF configuration [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/configure.html#configuration-file) but perhaps we could make it more visible to users since the automatic download feature is a very attractive feature for everyone. Should we add that information to the documentation [F.A.Q.](https://docs.esmvaltool.org/en/latest/faq.html) or the Github [one](https://github.com/ESMValGroup/ESMValTool/discussions/categories/q-a)?

I'm not sure whether the issue you are describing is very specific to DKRZ (lots of nodes with no internet access and a local ESGF node accessible from the machine). Would it help for DKRZ users to edit the [config-user file](https://github.com/ESMValGroup/ESMValCore/blob/2d3df9d923de3adf10739c90ab0372235b55b4ae/esmvalcore/config-user.yml#L96) like:
```yml
# Site-specific entries: DKRZ
# Uncomment the lines below to locate data on Mistral at DKRZ
# Use offline: false only on login and prepost nodes
#offline: true  
```
(but we should check if that holds for Mistral's successor)

**Comment by schlunma** [comment]
> Should we add that information to the documentation [F.A.Q.](https://docs.esmvaltool.org/en/latest/faq.html) ...?

Good idea, will do that!

> I'm not sure whether the issue you are describing is very specific to DKRZ (lots of nodes with no internet access and a local ESGF node accessible from the machine). Would it help for DKRZ users to edit the [config-user file](https://github.com/ESMValGroup/ESMValCore/blob/2d3df9d923de3adf10739c90ab0372235b55b4ae/esmvalcore/config-user.yml#L96) like:
> 
> ```yaml
> # Site-specific entries: DKRZ
> # Uncomment the lines below to locate data on Mistral at DKRZ
> # Use offline: false only on login and prepost nodes
> #offline: true  
> ```
> 
> (but we should check if that holds for Mistral's successor)

Also good idea, I will add these lines to the default config file.

**Comment by schlunma** [comment]
I realized that the first change needs to go into the tool.

For the second, I would like to wait for some answers on #2504.
