### ISSUE TITLE
[tests failing] `JULIA_LOAD_PATH` has changed and is causing test failures

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1443]
`JULIA_LOAD_PATH` has changed its formatting and it now gets a bunch of garble at the end eg `'JULIA_LOAD_PATH': '/tmp/pytest-of-valeriu/pytest-137/popen-gw1/test_initialize_env__jl_0/esmvaltool/install/Julia:@:@whynumba:@stdlib'` where the first bit `whynumba` is my conda environment name and `stdlib` is guff; it causes the task tests to fail eg [here](https://github.com/ESMValGroup/ESMValCore/runs/4969579136?check_suite_focus=true) - the env variable is set in `_task.py` at l.396:
```python
            # Set the julia virtual environment
            env['JULIA_LOAD_PATH'] = "{}:{}".format(
                DIAGNOSTICS.path / 'install' / 'Julia',
                os.environ.get('JULIA_LOAD_PATH', ''),
            )
```
and the garble is not localized to my machine or other specific machines, indeed if one runs this small script:
```python
import os

vg = os.environ.get('JULIA_LOAD_PATH')
print(vg)
```
gets that garble: `@:@whynumba:@stdlib` in my case. Note that the `@whynumba` is an env variable on its own:

`'JULIA_PROJECT': '@whynumba'`

no idea what `@stdlib` is in this case.

Julia installed:
```
(whynumba) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list julia
# packages in environment at /home/valeriu/miniconda3/envs/whynumba:
#
# Name                    Version                   Build  Channel
julia                     1.7.1                h989b2f6_3    conda-forge
```
reverting to a previous `_2` build is not fixing this. Currently I have no idea what is causing this, I'll investigate more tomorrow.

**Comment by valeriupredoi** [comment]
pinging @ngam and @mkitti since you guys might know and/or be impacted by this too (sorry, am abusing your patience with us and Julia :grin: )

**Comment by ngam** [comment]
This was a design choice to localize the julia paths, etc. but I am not sure about the end of the paths and how that works exactly. Usually this work perfectly fine for the intended purpose, but it may have unintended consequences we need to investigate. Perhaps @mkitti can weigh in; otherwise, I will try to resolve this soon to ensure these unintended consequences don't happen..

**Comment by ngam** [comment]
It's all done here btw: https://github.com/conda-forge/julia-feedstock/blob/master/recipe/scripts/activate.sh

**Comment by ngam** [comment]
You may get around by simply tweaking your env setting, but let's wait for @mkitti

**Comment by ngam** [comment]
> the env variable is set in `_task.py` at l.396:

Could you link this pls?

**Comment by valeriupredoi** [comment]
@ngam many thanks, mate! Sure, this is where we go about finding the path https://github.com/ESMValGroup/ESMValCore/blob/2d3df9d923de3adf10739c90ab0372235b55b4ae/esmvalcore/_task.py#L396 and we test for it with a simple monkeypatch - we can always append the new descriptor with your pointer here https://github.com/conda-forge/julia-feedstock/blob/41be9d1aa4fb8e48fd7e367a781a95dea076e222/recipe/scripts/activate.sh#L14 (cheers muchly for the pointer, it would have taken me a bit of digging through our own changes before I'd have had realized where the bit comes from :beer: ). What stumps me is why our tests decided to go south only now, looking at the env variables changes, guys put them in three weeks ago...

**Comment by mkitti** [comment]
In activate.sh (in the 1.7 branch), we are explicitly manipulating the load path and project:
https://github.com/conda-forge/julia-feedstock/blob/41be9d1aa4fb8e48fd7e367a781a95dea076e222/recipe/scripts/activate.sh#L12-L14

The meaning of these symbols is documented here:
https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_LOAD_PATH
https://docs.julialang.org/en/v1/base/constants/#Base.LOAD_PATH

Copying this inline for convenience:

* `@` refers to the "current active environment", the initial value of which is initially determined by the JULIA_PROJECT environment variable or the --project command-line option.

* `@stdlib` expands to the absolute path of the current Julia installation's standard library directory.

* `@name` refers to a named environment, which are stored in depots (see JULIA_DEPOT_PATH) under the environments subdirectory. The user's named environments are stored in `~/.julia/environments` so `@name` would refer to the environment in ~/.julia/environments/name if it exists and contains a Project.toml file. If name contains # characters, then they are replaced with the major, minor and patch components of the Julia version number. For example, if you are running Julia 1.2 then @v#.# expands to @v1.2 and will look for an environment by that name, typically at ~/.julia/environments/v1.2.

An unset `JULIA_LOAD_PATH` is equivalent to `@:@v#.#:@stdlib`. The means that code is loading in the following order:
1. The current active project
2. The top level `v1.7` environment (or as appropriate according the major and minor version of Julia)
3. The standard library.

With Julia 1.7 in conda-forge, we have
1. Added `"$CONDA_PREFIX/share/julia` as the primary depot path so that Julia packages and settings are stored in an environment  Julia contained with the conda environment.
2. Set the default `JULIA_PROJECT` to `@$CONDA_PREFIX` a named environment in the depot as described above.

**Comment by mkitti** [comment]
What is the actual failure in the end? It looks like you are just prepending the load path, which should be fine.

**Comment by zklaus** [comment]
@valeriupredoi, could you please indicate what the actual problem is and why you think Julia is connected? In the tests you link above, the errors seem to be from some provenance collection with no obvious relation to Julia.

**Comment by valeriupredoi** [comment]
@ngam @mkitti cheers guys! The problem is 100% at our end, and solvable by a three lines of code edit, I pinged you thinking that this was an unexpected behaviour, and you'd find a bug in Julia but it looks like this is actually due to good progess on your side (I like the idea of stacking the envs and identifying the load path based on env names!). Fo you guys and @zklaus - the error is creeping up for us only when we have an active installation of Julia from conda-forge (othewise the bit of the thest that deals with checking the path is ignored, when no installation is active), so `pytest tests/unit/task/test_diagnostic_task.py` fails this way:
```
>       assert task.env == env
E       AssertionError: assert {'JULIA_LOAD_...CKEND': 'Agg'} == {'JULIA_LOAD_...CKEND': 'Agg'}
E         Omitting 1 identical items, use -vv to show
E         Differing items:
E         {'JULIA_LOAD_PATH': '/tmp/pytest-of-valeriu/pytest-136/popen-gw1/test_initialize_env__jl_0/esmvaltool/install/Julia:@:@juliapath:@stdlib'} != {'JULIA_LOAD_PATH': '/tmp/pytest-of-valeriu/pytest-136/popen-gw1/test_initialize_env__jl_0/esmvaltool/install/Julia:'}
E         Use -v to get the full diff

tests/unit/task/test_diagnostic_task.py:46: AssertionError
```
which has a very easy fix by changing the `JULIA_LOAD_PATH` in our task builder. Klaus, your question about the GA test fails is valid - I thought the root cause of the test fail was maksed by the annoying behaviour of `flake8>=4` but we've merged that PR and now test fails should be well shown at run point, long story short I got no idea why the GA tests are failing there, this Julia-related fail was a serendipitous discovery since the same test module fails on GA and locally for me, after running it manually :grin:

**Comment by ngam** [comment]
@valeriupredoi, please tag us even if the issue is tangentially related to the julia-feedstock. This will help us in ensuring our solutions to the packages conundrum makes sense for downstream packages like this :)

We also can offer you pointers to specific changes instead of you looking on your own and wasting a lot of time figuring things out. I am very happy we are in constant communication with your team here ❤️

**Comment by valeriupredoi** [comment]
@ngam thanks a lot, man! You guys are awesome :beer: We've fixed that issue at our end, we'll close this once the PR gets merged, but we'll surely keep you in the loop (unless we decide to drop support for Julia, but it doesn't look that way anytime soon). I am actually going to propose a section on highlighting new informal partnerships that we bridge to be included with every new release we make, and I'll highlight the work we've done this past month with you guys in there :medal_military: Good weekend, mate!
