### ISSUE TITLE
`scipy` upgrade breaks our documentation builds

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1475]
Scipy evolving
```
https://conda.anaconda.org/conda-forge/linux-64/scipy-1.7.3-py310hea5193d_0.tar.bz2#9cbdb267370260306b57a63449f05ecf
https://conda.anaconda.org/conda-forge/linux-64/scipy-1.8.0-py310hea5193d_0.tar.bz2#7ddca9e5318955ddce85593547ff16b3
```
leads to our automatic doc builds spewing this

```
failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.scipy.org/doc/scipy/reference/objects.inv
```

I'll look into this imminently :+1:

**Comment by zklaus** [comment]
The conda package doesn't have much to do with this. The problem is that the Scipy doc server is horsed. We mentioned that briefly in https://github.com/ESMValGroup/ESMValCore/pull/673#issuecomment-1031257276, but it seems the situation is affecting many projects and will probably see some movement on the Scipy side. One issue that might be useful to track is scipy/scipy#14267.

**Comment by zklaus** [comment]
I found a temporary fix that we could use until upstream gets back in order. Replace the current intersphinx mapping entry with
```
 scipy=("https://scipy.github.io/devdocs/", None),
```

Should we do this, temporarily, to make our machinery work in these critical days?

**Comment by valeriupredoi** [comment]
Yis! Let's! Failing tests is a bummer

**Comment by schlunma** [comment]
Added in #1478
