### ISSUE TITLE
Some plots are not shown on `index.html` even though provenance information looks fine

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1535]
**Describe the bug**
While checking the results of the recent testing round I noticed that some plots are not shown in the website even though the provenance information is present:

https://esmvaltool.dkrz.de/shared/esmvaltool/v2.5.0-test-rc4/recipe_ecs_20220303_153631/

Examples of figures not shown: https://esmvaltool.dkrz.de/shared/esmvaltool/v2.5.0-test-rc4/recipe_ecs_20220303_153631/plots/cmip5/ecs/

**Comment by bouweandela** [comment]
It looks like this happens because only the output of the leaf nodes in the task tree gets written to index.html. I think this line:
https://github.com/ESMValGroup/ESMValCore/blob/4ad268a26185fe37acb85345c3608c6429240471/esmvalcore/_recipe.py#L1900
would need to be replaced by
```python
        for task in self.tasks.flatten():
```
But then some code changes would also be needed to make sure that preprocessor file descriptions are only added to index.html if they are not deleted afterwards.
