### ISSUE TITLE
Regularly run selected recipes to test for backwards compatibility

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1636]
The recipes will be made available by @axel-lauer @katjaweigel and ? in the ESMValTool recipes/testing folder. Recipes are expected to run in less than 5 minutes.

@bouweandela Will automate this so they run every week for testing, once the recipes are available.

**Comment by katjaweigel** [comment]
@axel-lauer should I add my recipe to your branch (else I have to create and change to the recipes/testing in mine)? 
 The recipe recipe_deangelis15nat_fig1_fast.yml is currently in the branch  fast_version_deangelis_for_test, I tested it now for v2.5 and it is working. To reliably keep it under 5 minutes (1 CPU, shared, Levante) I reduced it to one model. I made this test recipe, because the long version failed already for several new releases, but usually these fails are connected to model fixes, so the probability that this version with only one model is failing is much lower compared to the original version.

**Comment by bouweandela** [comment]
@katjaweigel It would be great if everyone who has developed testing recipes could make a separate pull request. Like that I will have some recipes to get started with as soon as possible and the others can add theirs later.

**Comment by axel-lauer** [comment]
@katjaweigel I agree with @bouweandela , separate pull request are preferable. I think reducing the number of datasets is fine as we want test recipes that are reasonably fast.

**Comment by katjaweigel** [comment]
@bouweandela and @axel-lauer ok, I created a pull request here: https://github.com/ESMValGroup/ESMValTool/pull/2685
