### ISSUE TITLE
Dataset problem: Nemo grid datasets cannot be regridded using iris-esmf

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#2014]
**Describe the dataset issue**
When trying to regrid ocean variables that are in a dataset that use the Nemo grid (CNRM, CMCC, EC-Earth, IPSL), the regridder in iris-esmf  fails due to the coordinates not being contiguous. In those particular datasets, removing the first grid point (which is always masked in ocean variables) seems to be enough in order to make the the coordinates contiguous and have the regridder work properly.

It would be good to have a fix that removes this point, even though it would mean that the data after fixing would have a different shape than the original data. I already worked on the fix, but it would be good to know if anyone has further comments.

**Assign the right people**
If you are already a member of the ESMValTool GitHub project, please assign Valeriu Predoi (valeriupredoi) and
Klaus Zimmermann (zklaus) to the issue. They will then check the issue raised and propagate it further to the
data model developers.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
  - Attach a text file with the output of `ncdump -h /path/to/file.nc`

Cheers :beer:

**Comment by stephenworsley** [comment]
There is also a new functionality in the latest version of iris-esmf-regrid where `ESMFAreaWeightedRegridder` now has a keyword `use_src_mask` where you can pass in a mask for all points which you don't want to regrid, if you have a common mask along all your data you can pass `use_src_mask`. If this covers the dicontiguities this *ought* to regrid the rest properly. I'd be interested to hear how you get on with it since it is quite new and could do with some testing against different grid types. Be aware that if you pass unmasked degenerate cells this can cause the regridder to hang.

**Comment by sloosvel** [comment]
Setting `use_src_mask` to True solved all contiguity issues, not only in these four datasets, but in other ones with more complicated grids, thanks for the tip! I think it would be good to automatically set `use_src_mask` in regrid.py if dealing with masked data, or ocean data. Even though this parameter can be set from the recipe, I think it would be more userfriendly if we set it automatically.

Even though the regridder works when using the mask, some datasets come out with a white line. It is probably due to the longitudes not being circular. 

I think this is something that is addressed when using the non-lazy [regrid_esmpy.py ](https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/preprocessor/_regrid_esmpy.py) routines. Should we do something similar before calling iris-esmf-regrid, or is this something that iris-esmf-regrid should be able to handle?

**Comment by stephenworsley** [comment]
I think you might be right about problems being due to circularity, I've seen this cause differences in behaviour occasionally. I don't know of any way to deal with this in iris-esmf-regrid currently, but it may be a possibility to add extra controls to creating regridders which allows curvilinear grids to be treated as if they were circular.
