### ISSUE TITLE
`extract_levels` preprocessor realizes source levels

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2114]
The `extract_levels` preprocessor preprocessor function realizes the source levels. These can be as big as the data for cubes with a hybrid sigma coordinate. Example with a 15GB file where this becomes problematic:
```python
from esmvalcore.dataset import Dataset
from esmvalcore.preprocessor import extract_levels
ds = Dataset(
  short_name='clw',
  mip='Amon',
  project='CMIP6',
  dataset='CESM2-WACCM',
  exp='historical',
  ensemble='r1i1p1f1',
  grid='gn',
  timerange='1850/2014',
)
cube = ds.load()
result = extract_levels(
  cube,
  levels=[0, 100000],
  scheme='linear',
  coordinate='air_pressure',
)
```

**Comment by bouweandela** [comment]
The result of printing `cube.coords()` is:
```
[<DimCoord: time / (days since 1850-1-1 00:00:00)  [...]+bounds  shape(1980,)>,
 <DimCoord: atmosphere_hybrid_sigma_pressure_coordinate / (1)  [0.993, ...]+bounds  shape(70,)>,
 <DimCoord: latitude / (degrees_north)  [-90. , -89.058, ..., 89.058, 90. ]+bounds  shape(192,)>,
 <DimCoord: longitude / (degrees_east)  [ 0. , 1.25, ..., 357.5 , 358.75]+bounds  shape(288,)>,
 <AuxCoord: vertical coordinate formula term: reference pressure / (Pa)  [...]>,
 <AuxCoord: surface_air_pressure / (Pa)  <lazy>  shape(1980, 192, 288)>,
 <AuxCoord: vertical coordinate formula term: a(k) / (1)  [0., ...]+bounds  shape(70,)>,
 <AuxCoord: vertical coordinate formula term: b(k) / (1)  [0.993, ...]+bounds  shape(70,)>,
 <AuxCoord: vertical pressure / (Pa)  [0., ...]+bounds  shape(70,)>,
 <AuxCoord: air_pressure / (Pa)  <lazy>+bounds  shape(1980, 70, 192, 288)>]
```
@schlunma I see the `air_pressure` coordinate has a time dimension. Does this coordinate really change in time?

**Comment by schlunma** [comment]
Yes. Since it's an `atmosphere_hybrid_sigma_pressure_coordinate`, the formula to calculate `air_pressure` is

```
p[t, z, y, t] = a[z] * p0 + b[z] * ps[t, y, x]
```

as also described [here](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris.aux_factory.html#iris.aux_factory.HybridPressureFactory). The corresponding variables in your case are:

- `p0`: `vertical coordinate formula term: reference pressure`
- `a`: `vertical coordinate formula term: a(k)`
- `b`: `vertical coordinate formula term: b(k)`
- `ps`: `surface_air_pressure`

**Comment by bouweandela** [comment]
Thanks, that's good to know. I guess we'll just need to update the preprocessor so it uses `.core_points()` instead of `.points` everywhere.

**Comment by valeriupredoi** [comment]
yes, there are a few things at play here (apols for the print statements, I am, after all, from the 1980s):
```python
    print(src_levels)
    src_levels_broadcast = broadcast_to_shape(src_levels.points, cube.shape,
                                              cube.coord_dims(src_levels))

    # force mask onto data as nan's
    npx = get_array_module(cube.core_data())
    data = npx.ma.filled(cube.core_data(), np.nan)

    # daskify
    # levels = da.from_array(levels)
    # src_levels_broadcast = da.from_array(src_levels_broadcast)
    print(type(levels))
    print(type(data))
    print(type(src_levels_broadcast))

    print("Before stratify")
    # Now perform the actual vertical interpolation.
    new_data = stratify.interpolate(levels,
                                    src_levels_broadcast,
                                    data,
                                    axis=z_axis,
                                    interpolation=interpolation,
                                    extrapolation=extrapolation)
```

`src_levels` is NOT lazy - that needs be lazy otherwise `broadcast_to_shape` from iris checks in a ton of memory; then `levels` is not lazy (it's an ndarray), and if those two `levels` and `src_levels_broadcast` are not lazy then stratift.interpolate chucks in a ton of memory on top of the braodcast_to_shape (as @schlunma lazied it)

**Comment by bouweandela** [comment]
Reported a related problem in https://github.com/SciTools/iris/issues/5457.
