### ISSUE TITLE
Preprocessor functions that made checker fail

### ISSUE THREAD

**Issue by jvegasbsc** [ESMValGroup/ESMValCore#212]
In pull request #87 I added the option to compute variances for several time periods. That functionality made the checker crash because units were squared.

The question is, we want to allow this kind of functions on the preprocessor? If that's true, when we want to apply the data checker?

Other (potential) preprocessor functions that can be affected:

- Corner cases in regrid than can make values go outside `valid_min` and `valid_max` range
- Anomalies: can make values go outside `valid_min` and `valid_max` range
- Standarized anomalies ( anomalies / std ): they don't have units

**Comment by bouweandela** [comment]
We could also consider merging the function `cmor_check_data` with `cmor_check_metadata`, since we do not actually check the data anyway. That would also solve this problem, since `cmor_check_metadata` is run right after loading the data. @jvegasbsc @mattiarighi Do you think this could be an acceptable solution?
