### ISSUE TITLE
`mask_fillvalues` and `mask_multimodel` recompute mask from all input cubes for every output cube

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2521]
Because [`mask_fillvalues`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.mask_fillvalues) and [`mask_multimodel`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.mask_multimodel) are now lazy, they recompute the mask based on all the input cube for every output cube. This is slow and unnecessary because the mask is the same for every output cube.

**Comment by valeriupredoi** [comment]
could you maybe tell us more about the process, pls, bud? `mask_multimodels` calls `_multimodel_mask_cubes(cubes, shape)` or the equivalent for `products`, where a composite mask is built from the mask of each `cube` in `cubes` so the iteration is needed due to each cube having a different mask - you saying this iteration is done for each cube a la:

```python
for cube in cubes:
    _multimodel_mask_cubes(cubes, shape)  # that will, in turn, loop over cubes again
```
?

**Comment by valeriupredoi** [comment]
thanks, bud! I need to read this carefully tomorrow, am just about to go home shove a pizza in the oven :pizza:
