### ISSUE TITLE
MemoryError for 3D vars in preprocessor function daily_statistics

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValCore#275]
According to CMIP tables, the 3D variables of ERA-Interim with daily frequency are in 8 pressure levels and with monthly frequency are in 19 levels. For example, when working with preprocessor functions like daily_statistics on daily Geopotential (its CMIP name is zg), it gives the error as: 

MemoryError: Unable to allocate array with shape (1464, 8, 241, 480) and data type float32

During handling of the above exception, another exception occurred:
MemoryError: Failed to realise the lazy data as there was not enough memory available.
The data shape would have been (1464, 8, 241, 480) with dtype('float32').
 Consider freeing up variables or indexing the data before trying again.

**Comment by valeriupredoi** [comment]
your operation would have to allocate (roughly) 5GB of RAM to store the data array and operate on it; unfortunately, since this operation uses `cube.aggregated_by()` *and* this operation is not yet lazy https://scitools.org.uk/iris/docs/latest/iris/iris/cube.html#iris.cube.Cube.aggregated_by you will have to run your analysis on a machine with a bit more memory available :beer:

**Comment by bouweandela** [comment]
See https://github.com/SciTools/iris/issues/3280

**Comment by bouweandela** [comment]
The current implementation uses about 18 GB or RAM to compute daily statistics on a 5 GB cube, i.e. shape (1464, 8, 241, 480) with float32.

**Comment by valeriupredoi** [comment]
can we close this @SarahAlidoost :beer:
