### ISSUE TITLE
Bug in regrid time

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#339]
Hi,

I think I've found a pair of bugs in the regrid time preprocessor.
 
Firstly, it isn't set up to re-grid annual data (no big deal - easy fix). Just add these lines at line 531 of `_time.py`. 
```
    elif frequency == 'year':
        cube.coord('time').cells = [
            datetime.datetime(t.year, 7, 1, 0, 0, 0) for t in time_c
        ]
```
Secondly, the order of operations is incorrect. At the moment, it changes the time units in line 501, then loads the time afterwards in line 507. This means that the time data is loaded using `gregorian` units, from a netcdf file which might not be in gregorian units!

Ie: This line:
https://github.com/ESMValGroup/ESMValCore/blob/11c53fa21e39301cba26ce941a233baad51b39de/esmvalcore/preprocessor/_time.py#L507

should be after this line:
https://github.com/ESMValGroup/ESMValCore/blob/11c53fa21e39301cba26ce941a233baad51b39de/esmvalcore/preprocessor/_time.py#L501

not before!

**Comment by ledm** [comment]
I think I'm interpreting it differently. 

Line 501 sets the calendar to the final shared calendar (Gregorian) and line 507 loads the time data. This means that if the data is not already in a gregorian calendar, then the time values will be calculated using the incorrect calendar.

In my case, this preprocessor was moving data from 2005 in a 360 day calendar to 2003 in the Gregorian calendar. It is wrong. This is a bug.

**Comment by valeriupredoi** [comment]
> In my case, this preprocessor was moving data from 2005 in a 360 day calendar to 2003 in the Gregorian calendar. It is wrong. This is a bug.

if your data is shifted by 2 years in the *past* when you are going from a a 360-day calendar to a Gregorian calendar (365-day), when in fact it should be shifted in the future (since Gregorian has 5 more days per year), that means there is a serious issue with something else. Regridding (poorly called, more like standardizing) time points, done in between lines 506-530 can not be done on cubes with differing calendars (the monthly data can, at day step, since we are setting the day at the middle of the month, but even then, there may be shifts in years due to leap or no leap, but none of the other higher frequency can be done)

**Comment by valeriupredoi** [comment]
in any case, setting the calendar in l.501 is just a synthetic process, since that is not actually changing the actual time points and the units, since the units are CMOR set after check/fix metadata they will be `units=Unit('days since 1850-1-1 00:00:00', calendar='gregorian')` so the time regridding can operate on cubes with same units and operations between cubes can happen without iris complaining of different units. You should look closer at your data and what you do with it so you can identify what shifts your time so badly :beer:

**Comment by valeriupredoi** [comment]
for Pete's sake, you're right! Fixing it now :beer:

**Comment by ledm** [comment]
> for Pete's sake, you're right! Fixing it now

Feeling pretty vindicated now, lol. Cheers V.

**Comment by valeriupredoi** [comment]
#351

**Comment by valeriupredoi** [comment]
#351 is ready to be merged, been ready for a while :beer:
