### ISSUE TITLE
recipe: using exp: [historical, ssp126] with overlapping data

### ISSUE THREAD

**Issue by mathause** [ESMValGroup/ESMValCore#349]
Theoretically it is possible to combine experiments in the recipe as `{exp: [historical, ssp585], ...}`. Practically this does not work as many models have an overlap (e.g. historical going further than 2014) and then this technique fails (see e.g this [recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_cox18nature.yml#L51-L52)). Is there a way to achieve this? Can a per-experiment `end_year` or `start_year` be defined?

**Comment by npgillett** [comment]
This is an issue with FGOALS-g3 historical Amon tas and FGOALS-g3 ssp245 Amon tas, r1i1p1f1. The dates overlap (the historical tas continues until Dec 2016, but the ssp245 tas starts in Jan 2014) and I need to concatenate these experiments.... will have to write a one-off fix. Just reading in separately is not practical, because I am reading this in along with ~1000 other expertiments and I want start date 1850 and end date 2019.
