### ISSUE TITLE
Cube concatenation failure with IPSL cmip6 Atmos

### ISSUE THREAD

**Issue by earnone** [ESMValGroup/ESMValCore#490]
**Describe the bug**
Running the `hyint` recipe on the IPSL-CM6A-LR cmip6 model fails when attempting to concatenate historical with the ssp585 pr day projection. The files look fine and can be concatenated with e.g. cdo. Both historical and ssp585 data run smoothly through the preprocessing independently.

Error message:
```
2020-02-13 13:16:56,433 UTC [56691] ERROR   From Cell(point=real_datetime(1850, 1, 1, 12, 0), bound=(real_datetime(1850, 1, 1, 0, 0), real_datetime(1850, 1, 2, 0, 0))) to Cell(point=real_datetime(2014, 12, 31, 12, 0), bound=(real_datetime(2014, 12, 31, 0, 0), real_datetime(2015, 1, 1, 0, 0)))

2020-02-13 13:16:56,437 UTC [56691] ERROR   From Cell(point=real_datetime(2015, 1, 1, 12, 0), bound=(real_datetime(2015, 1, 1, 0, 0), real_datetime(2015, 1, 2, 0, 0))) to Cell(point=real_datetime(2100, 12, 31, 12, 0), bound=(real_datetime(2100, 12, 31, 0, 0), real_datetime(2101, 1, 1, 0, 0)))

2020-02-13 13:16:56,437 UTC [56691] ERROR   Failed to run concatenate([<iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 60265; latitude: 143; longitude: 144)>, <iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 31411; latitude: 143; longitude: 144)>], {})

```

Here is the [main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/4199252/main_log_debug.txt).

Here is a test recipe:
[recipe_hyint_test_IPSL_cmip6_yml.txt].(https://github.com/ESMValGroup/ESMValCore/files/4199150/recipe_hyint_test_IPSL_cmip6_yml.txt)
It crosses 2014/2015 where the concatenation occurs. It takes a few minutes with these settings if everything is ok. If you change the dates make sure `norm_years` fall within and is shorter than the given range. 

@valeriupredoi  @jvegasbsc - same problem as #282?

**Comment by valeriupredoi** [comment]
cheers @earnone - will be all over this in a short while today :beer:

**Comment by valeriupredoi** [comment]
@earnone this is not related to #282 - the problem here is simple: you are using daily data and the first cube ends at 2014-12-31 12:00:00 and the next cube starts at 2015-01-01 12:00:00 -> there is no overlap so the concatenation can not produce a result! Note that the improved concatenation assumes a minimal overlap between the cubes (minimal = at least one time point). But since there is none, it fails as it should be. Annoying act is that iris is not able to concatenate two **separate** cubes - using `concatenate_cube()` that guarantees a single output concatenated cube fails due to `time` differing in metadata from the two cubes:

```
standard_name='time', calendar='gregorian', long_name='Time axis', var_name='time', attributes={'time_origin': '1850-01-01 00:00:00'}
standard_name='time', calendar='gregorian', long_name='Time axis', var_name='time', attributes={'time_origin': '2015-01-01 00:00:00'}
```
it's the `attributes` that differ! @jvegasbsc we should remove those in the metadata check+fix

**Comment by earnone** [comment]
@valeriupredoi the concatenation works fine when subsequent files are adjacent in time (as it is in this case), no need for overlap. It works for all other models. I think it is as you found the wrong `attributes` for the `'time_origin' `

**Comment by valeriupredoi** [comment]
not just a data fix but rather a perennial metadata fix in `fix.py` - @jvegasbsc you wanna do it or should I do it?

**Comment by valeriupredoi** [comment]
@zklaus is `coord("time"){attributes}` a CMOR accepted field?

**Comment by valeriupredoi** [comment]
the CMIP6 coords table mentions nothing about it:
```
        "time": {
            "standard_name": "time",
            "units": "days since ?",
            "axis": "T",
            "long_name": "time",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "yes",
            "out_name": "time",
            "positive": "",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "",
            "valid_min": "",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": ""
        },
```

**Comment by valeriupredoi** [comment]
removing the time attributes allows concatenation and recipe goes through to finish line :beer:

**Comment by zklaus** [comment]
That attribute is indeed not cmip6 and could simply be deleted.

In principle, the problem is also in the official attribute for this purpose, the units for time which are given as
```
time:units = "days since 2015-01-01 00:00:00" ;
```
but should be "days since 1850-01-01" because it is a continuation of a historical run.
However, this is fixed automatically already by ESMValTool, so adding a fix that removes the time_origin attribute should be enough.

**Comment by valeriupredoi** [comment]
sweet - fix in https://github.com/ESMValGroup/ESMValCore/pull/495

**Comment by valeriupredoi** [comment]
> but should be "days since 1850-01-01" because it is a continuation of a historical run.
However, this is fixed automatically already by ESMValTool, so adding a fix that removes the time_origin attribute should be enough.

That's indeed fixed proper in check->fix.py
