### ISSUE TITLE
Preprocessing overlapping data not implemented yet

### ISSUE THREAD

**Issue by alasdairhunter** [ESMValGroup/ESMValCore#54]
Hi,
I am having an issue with the preprocessing when trying to run a diagnostic which uses two variables from a single model:
https://github.com/ESMValGroup/ESMValTool/blob/MAGIC_BSC/esmvaltool/recipes/recipe_diurnal_temperature_index_wp7.yml
   
  An unexpected problem prevented concatenation.
  Expected only a single cube, found 2.

I guess this is just a minor error in our .yml file. Do you have an example of any other diagnostics which load two (or more) variables from a single model for use as input for a single R script (or Python script).

**Comment by mattiarighi** [comment]
#280 seems to have solved this issue as well.

I tried reading the following dataset (see also @bjoernbroetz's [comment above](https://github.com/ESMValGroup/ESMValCore/issues/54#issuecomment-437858210)):
```
  - {dataset: IPSL-CM5A-LR, project: CMIP5, exp: historical, mip: day, ensemble: r1i1p1, start_year: 1998, end_year: 2003}
```
which I would expect to give problems, since the input directory contains overlapping files:
```
/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ/IPSL/IPSL-CM5A-LR/historical/day/atmos/day/r1i1p1/v20110915/tasmin/tasmin_day_IPSL-CM5A-LR_historical_r1i1p1_19500101-19991231.nc
/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ/IPSL/IPSL-CM5A-LR/historical/day/atmos/day/r1i1p1/v20110915/tasmin/tasmin_day_IPSL-CM5A-LR_historical_r1i1p1_19500101-20051231.nc
```
but it went through without errors.

However, from the log I cannot understand which of the two was actually used.

@valeriupredoi ?

**Comment by valeriupredoi** [comment]
did you read the debug log? It's all there @mattiarighi (like in the Da Vinci Code :grin: )

**Comment by valeriupredoi** [comment]
yay! :tada:
