### ISSUE TITLE
How to quickly get to the log.txt for debugging?

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#612]
Forwarded question:
While working on a new or improved diagnostic, I often find myself adding many print statements. I then have to look up the output directory and manually navigate to the log.txt, because the output folder always changes. 

Two things I tried so far: 
- Use the "re-run this diagnostic script" option to at least make sure the output folder doesn't change.
- Define an alias such as (better suggestions welcome):
```Shell
output=$(ls -t -d /my/output/dir/* | head -1) ; find $output "log.txt" -exec tail {} \;
```
I was wondering if there's better solution, e.g. is it possible to set a debug flag and print the log.txt to stdout, or something along those lines? What do you normally use?

**Comment by bouweandela** [comment]
Hi Peter,

- The first method you tried might be most convenient, because it avoids re-running the preprocessors, so it's much faster when debugging a diagnostic script.
- A similar approach to the second method you mentioned is documented here: https://esmvaltool.readthedocs.io/en/latest/faq.html#create-a-symbolic-link-to-the-latest-output-directory
- Printing log.txt is only possible if you're not running `esmvaltool` in parallel, because otherwise the output would be mixed from all different threads. I believe we have an open issue about this somewhere, but I cannot find it at the moment. The idea would be to always print the diagnostic log on stdout if you run `esmvaltool` with `max_parallel_tasks: 1` in config-user.yml.

**Comment by Peter9192** [comment]
Thanks Bouwe!

> otherwise the output would be mixed from all different threads

Yeah, that's what I thought.

> I believe we have an open issue about this somewhere, but I cannot find it at the moment

Do you mean [this one?](https://github.com/ESMValGroup/ESMValCore/issues/65)

**Comment by bouweandela** [comment]
> Do you mean this one?

No, that's about providing good information for debugging errors with the preprocessor.

**Comment by bouweandela** [comment]
Found it: #63

**Comment by bouweandela** [comment]
@Peter9192 Does this answer your question? Can the issue be closed, or do you feel that something should still be done here?
