### ISSUE TITLE
Make user configuration file more user friendly

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#64]
- Do not use the template as a default because it never works
- If no config file is suppllied, look if a file ~/.esmvaltool/config-user.yml exists and use that
- If it doesn't exist, create it and tell the user to customize it (at least the paths section). If the user is on a known cluster, e.g. Jasmin, Mistral, etc, automatically use the right path

**Comment by ledm** [comment]
At our tutorial, @rjp23 has brought up the issues with the `config-user.yml`. 

It's frustrating that users need to edit this file, but the documentation is not explicit. There should be a big red banner somewhere about it. 

It should be easier for users to get started. Would it be possible to include the correct rootpath variables, but commented out in the standard `user-config.yml`?

Alternatively, perhaps there is an even better solution where the rootpaths are instead defined in `config-developpers.yml` so that user's don't have to define standardised paths in their `config-user.yml` (if they're working on a standard machine like jasmin) file?

**Comment by bouweandela** [comment]
Related issues https://github.com/ESMValGroup/ESMValTool/issues/1278, https://github.com/ESMValGroup/ESMValCore/issues/100, https://github.com/ESMValGroup/ESMValCore/issues/125, https://github.com/ESMValGroup/ESMValCore/issues/93

**Comment by bouweandela** [comment]
> It's frustrating that users need to edit this file, but the documentation is not explicit. There should be a big red banner somewhere about it.

@ledm Note that pretty extensive documentation is now available here: https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/quickstart/find_data.html
However, this really should be linked from https://esmvaltool.readthedocs.io/en/latest/quickstart/configuration.html

**Comment by schlunma** [comment]
Can this be closed? I think most of the issues listed are solved.

**Comment by bouweandela** [comment]
Yes, except for automatically finding out which cluster we're on, but let's close this.
