### ISSUE TITLE
Run tests for all supported Python versions

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#662]
At the moment we only test with the latest Python version (3.8), but we claim to support Python 3.6 and 3.7 as well. To ensure that this actually works, it would be good to test with those Python versions too on CircleCI.

**Comment by valeriupredoi** [comment]
I am a bit weary of this because that would mean changing the CI environment quite drastically ie recreating the whole env for each Python version - that will take time, quite a bit of it. Can we not just support and test with only the latest Python version? Or alternatively, run those tests not everytime there is a minor code change but rather once in a blue moon? :new_moon_with_face:

**Comment by bouweandela** [comment]
We could run the tests for the master branch once a day.

**Comment by valeriupredoi** [comment]
we could use [Github Actions](https://lab.github.com/githubtraining/github-actions:-continuous-integration) to do that since that one supports different OS's and Python versions for free - tyhat can actually allow us to run the MacOS tests too
