### ISSUE TITLE
Couple comments/questions about the new CLI

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#698]
@jvegasbsc terrific job on the new CLI, mate! :beer: A couple comments I failed to raise before it got merged, but it don't matter too much:

- I am a bit uneasy about the use of `INFO    [31797] Using config file ~/.esmvaltool/config-user.yml` if the user doesn't specify a config file via `--config-file`: first off, that directory doesn't exist and it doesn't get created automatically (which is also a good thing!) and second, it may lead to confusion on the user's side if they forget to update the file for certain runs; to the very least I'd recommend changing the message to a warning; I would also make the code not fail if `~/.esmvaltool` doesn't exist, but create it automatically but not place a config file there and exit with a clear message a la `You don't have a config-user.yml file in ~/.esmvaltool.`
- running in `log_level: debug` is much faster now (wow!) - can you pls explain the difference in performance vs previous CLI implementation?

Cheers buddy :beer:

**Comment by jvegasbsc** [comment]
> I am a bit uneasy about the use of INFO [31797] Using config file ~/.esmvaltool/config-user.yml if the user doesn't specify a config file via --config-file

I understand your issue, but I think is because of old habits. A new user will probably get its `config_user` by calling `esmvaltool config get-config-user` which magically creates it in the default location. We are used to change config file between runs, but this is not something that a user will do frequently.

Also, bear in mind that we don't need to use so many config files now, as every key in it can be set as a run flag, so no more need to change `save_intermediate_cubes` and `log_level` in the config user. 

I thought about adding *two* config_users to the folder, one of them with a default debug configuration that will be used when running with the `--debug` flag

**Comment by jvegasbsc** [comment]
> running in log_level: debug is much faster now (wow!) - can you pls explain the difference in performance vs previous CLI implementation?

The only performance related change that I did was to put all the imports inside the functions of the CLI, leaving at the top only the ones required by the CLI itself. This should only affect startup time of the executable, though.

**Comment by valeriupredoi** [comment]
cheers Javi, yeah was thinking the same - but I still think we should change to a warning when printing the message about the default config-file, easier to find in the log for a user, what do you think? :beer:

**Comment by jvegasbsc** [comment]
> a warning when printing the message about the default config-file, easier to find in the log for a user, what do you think?

A warning when running using the default option? If it really becomes the default way to run it will be just noise...

**Comment by valeriupredoi** [comment]
ok cool, let's just leave it as is for now; I might have to be a pain in the rear in the future, but for now cheers for clarifying these points, bud :beer:
