### ISSUE TITLE
Installation on Windows doesn't work from stock

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#701]
So the new GitHub Actions testing I started implementing [here](https://github.com/ESMValGroup/ESMValCore/pull/700) is already proving useful: I have discovered that the current environment can not be built on Windows as it is, since `esmpy` and `libunwind` don't have Windows versions. Do we want to do anything about this or we just say we don't support installation on Windows? If it was me I'd argue we should strive to support windows too, lots of potential users (that are scientists and not software engineers) use Windows :beer:

**Comment by jvegasbsc** [comment]
I do not think that having native support is something easy to achieve, lots of scientific packages are UNIX only. But does not mean that Windows users are not able to use ESMValTool. In fact, I am working using a Windows laptop right now using the Windows Subsystem for Linux. Users just need to install an application from the store and then follow the Linux installation steps. This is the one for ubuntu (https://www.microsoft.com/es-es/p/ubuntu/9nblggh4msv6) but there are lots of other distributions available.

You also have the option to run using the docker container, which is also very easy to install on Windows using Docker desktop

I agree with you in that we should add a section in the documentation explaining how to use ESMValTool from Windows, because I think most of the people do not know about this two options.

**Comment by valeriupredoi** [comment]
very cool, Javi! Well, I surely didn't know :grin: - any way you can update the Windows tests in #700 so we can autoamte the installation testing for Windows? :beer:

**Comment by bouweandela** [comment]
@nielsdrost Recently added instructions for installing ESMValTool on Windows to the tutorial: https://esmvalgroup.github.io/tutorial/02-installation/index.html

**Comment by jvegasbsc** [comment]
> @nielsdrost Recently added instructions for installing ESMValTool on Windows to the tutorial: https://esmvalgroup.github.io/tutorial/02-installation/index.html

Great, we can move it to the documentation. 

On the other hand, how we ensure that the tutorial and the documentation are aligned? I bet this is not the only "duplication" we have. Maybe we should put comments in both telling something like "if you are updating this, please update also this section of the documentation/tutorial"?

**Comment by valeriupredoi** [comment]
sorry guys, where are the Windows installation instructions now? I am trying to update and test the Github Actions tests :beer:

**Comment by bouweandela** [comment]
The tutorial repo was renamed, they now live here: https://esmvalgroup.github.io/ESMValTool_Tutorial/02-installation/index.html

**Comment by valeriupredoi** [comment]
cheers @bouweandela - unfortunately enabling an automated test for the WSL stuff is nye on the impossible - I removed the Win workflow from Github Actions, all the others are passing nicely though :beer:
