### ISSUE TITLE
tracking of the data versions used to run a receipe

### ISSUE THREAD

**Issue by jgriesfeller** [ESMValGroup/ESMValCore#742]
In the IS-ENES3 project there's this small task named 'Version documentation of **utilized** observations' that asks for version info of observations to be added to the provenance information. This info is mostly important for data sets that change their version frequently (e.g. AERONET updates once a week, but does not keep elder versions for reference). 
But given that during the last part of the CMIP6 data submission phase several models provided several data versions on ESGF at a time, this info might be interesting at the mode level as well. It's somewhat hidden in the file paths of the model data.

In earlier checks I did, I assumed that the version info in the log files does exactly that (without confirming unfortunately), but when looked at it deeper now that I am writing the delivery report it appears to be 'just' the version number of the cmorizer or the reading routine for the data set. Is that true?
According to the work plan, this should have been in the ESMValTool by July 2020.

The info that should be tracked is e.g for the obs4mips data in the general attribute named 'version'

**Comment by bouweandela** [comment]
The information is not present in the log files, but in the provenance (in [W3C prov XML format](https://www.w3.org/TR/prov-xml/) that the ESMValCore records.

All paths and global attributes of input NetCDF files are stored in the _provenance.xml files that are produced for each figure/output file, so in some cases recording the provenance will work just fine:
- For data that has the version stored as a global NetCDF attribute
- For CMIP data that is stored in a directory structure where the version is included in the filename
- For observations that require reformatting, we ask the authors of the CMORizers scripts to provide the version number, see e.g.
https://github.com/ESMValGroup/ESMValTool/blob/837c092fcd1ba8043f248d4c3d6875af532b186c/esmvaltool/cmorizers/obs/cmor_config/CERES-EBAF.yml#L8, this version number is recorded both as a global attribute and in the filename

It does not work for CMIP data that is stored with e.g. all files in a single directory. Unfortunately, CMIP data does not contain the version as a global NetCDF attribute, so depending on how the user stores the data, it may or may not be possible to retrieve the version number. This is also a problem when some fixes need to be applied to the dataset before it is CMOR/CMIP compliant: we try to implement these fixes in a way that they work regardless of whether the problem is present or not, but unfortunately this is not always possible.

**Comment by jgriesfeller** [comment]
@bouweandela Thanks for the information. I will put this information into my deliverable document including the link to this issue.

**Comment by jgriesfeller** [comment]
Since the IS-ENES3 activity covers observational data only (for which the requirement is met), I will close this issue.
