### ISSUE TITLE
Add support for named scientific regions in extract_shape

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#758]
The `extract_shape` preprocessor currently requires a shapefile path in the recipe. It would be nice to support named scientific regions as well, such as the SREX or AR6 regions. We could probably reuse some of [`regionmask`'s](https://regionmask.readthedocs.io/en/latest/defined_scientific.html) functionality, like so:

```Python
shape = regionmask.defined_regions.srex['NEU'].polygon
```

In the recipe, you could then do something like:

```YAML
extract_shape:
  scientific_regions: SREX
  region_name: NEU
  region_number: 11  # one of name or number should be enough.
```

**Would you be able to help out?**
Yes

**Comment by Peter9192** [comment]
I looked a bit more into regionmask, and it seems to do very similar things that we do in the extract_shape preprocessor. Has it ever been considered to use regionmask in our preprocessor? If so, why did we decide against? And if not, would it make sense to put some effort into this?

**Comment by bouweandela** [comment]
Would there be some overlap with the [`extract_named_regions`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.extract_named_regions) preprocessor function?

If you want the keyword arguments proposed above, I would recommend making a completely new preprocessor function, because there does not seem to be much overlap with `extract_shape`. Another option could be to change the current `extract_shape` preprocessor function so the `shapefile` argument can be either a shapefile or a named region from the regionmask package.

> Has it ever been considered to use regionmask in our preprocessor? 

Not really, but it could be an option, it looks like a useful package. My only concern is that it is developed by a single person, but if we adopt it we could also contribute if there are problems.

> would it make sense to put some effort into this?

It would make sense to put effort in it if the current function does work well enough.

**Comment by Peter9192** [comment]
Thanks Bouwe!

From what I understand, the `extract_named_regions` looks for an additional `region` coordinate that must be present in the cube. That's quite different.

**Comment by bouweandela** [comment]
OK, I thought that would correspond to the AR6 regions.

**Comment by bouweandela** [comment]
I also found the ASCEND package by the Met Office, which extract shapes from iris cubes, not sure what the status exactly is though: https://github.com/informatics-lab/covid-19_shapecutter/blob/master/shape_utils.py

**Comment by lukasbrunner** [comment]
Okay I'm continuing this here for a bit: https://github.com/ESMValGroup/ESMValTool/issues/2098

I played around a bit and ended up just adding all AR6 shapefiles to the aux data and then referring to them as needed. Now I wonder if the easiest solution would not be to just add the shapefiles to the core in some path (or have a download routine once they are needed). Then what Peter suggested at the beginning

```yaml
extract_shape:
  scientific_regions: SREX
  region_name: NEU
  region_number: 11  # one of name or number should be enough.
```

Could be done in the background by just using what is there already

```yaml
shapefile: 'somepath/shapefiles/<scientific_region>/<region_name>.shp'
method: contains
crop: true
```

Although it would be convenient to be able to easily combine regions (for example Europe as ['NEU', 'CEU', 'MED'] but maybe this could still easily work with this approach? For this I don't understand enough what is actually happening when cutting the regions .

**Comment by Peter9192** [comment]
I haven't really looked into the code, but could this functionality be combined with this feature that was recently implemented: https://github.com/ESMValGroup/ESMValCore/pull/764?

**Comment by bouweandela** [comment]
>  Now I wonder if the easiest solution would not be to just add the shapefiles to the core in some path (or have a download routine once they are needed). 

What is the size of the files? If they are really small, they can be included with the core, but it's more than a megabyte or so a download routine would be better. The latter could save the files to `auxiliary_data_dir` as defined in config-user.yml, that's also how it's done for certain cartopy downloads.

**Comment by lukasbrunner** [comment]
See attached file for the filesizes - seems to be manageable. I extracted them from regionmask, [here](https://github.com/mathause/regionmask/tree/master/data) is also the file they are based on. But if I understand #764 correctly it might even be better to have them as only one file instead of one file per region?

[shapefiles_list.txt](https://github.com/ESMValGroup/ESMValCore/files/6228107/shapefiles_list.txt)

**Comment by schlunma** [comment]
In light of #2007 I'd like to revive this discussion here and propose to add the AR6 region shape file to a new directory `esmvalcore/preprocessor/shapefiles/ar6.shp`. This file is publicly available under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/legalcode) from [Zenodo](https://doi.org/10.5281/zenodo.5176260) and has a size of 341 KiB. It can be used in the recipe with a simple

```yaml
extract_shape:
  shapefile: ar6
  ...
```

so it would be fully backwards compatible. Any opinions?

**Comment by zklaus** [comment]
Sounds good. At the moment, we are relying on the same file in the auxiliary directory, which is a bit of a hassle.

**Comment by schlunma** [comment]
Implemented in https://github.com/ESMValGroup/ESMValCore/pull/2008
