### ISSUE TITLE
Example config file could use some improvements

### ISSUE THREAD

**Issue by nielsdrost** [ESMValGroup/ESMValCore#794]
Why doing the tutorial, I noticed that the default example config file could use some tweaks. For instance:

* There is no example of a flat directory with files in the config, even though this is used in the tutorial
* obs4mips is not a project in the example data locations

**Comment by bouweandela** [comment]
> There is no example of a flat directory with files in the config, even though this is used in the tutorial

I'm not sure if it's a good idea to recommend using such a directory structure, because you lose the version information of CMIP models if you do not store that in the path. At the moment we do not use the version information for applying fixes, but in the future we probably should start using that to know if a model was already fixed or not.

**Comment by bouweandela** [comment]
obs4MIPs is now listed in the example file.
