### ISSUE TITLE
Discussion point: use Github Packages for the ESMValGroup project?

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#830]
I am not sure if there's even a hint of a need to do that - but am raising the question up for debate - do we want to think about using Github Packages at all? I see they have a nice docker format (all other formats like npm or Ruby don't seem to be useful), has any of our engineers @nielsdrost @bouweandela @jvegasbsc et al used Github Packages in the past? Docs [here](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages)

**Comment by nielsdrost** [comment]
Nop, sorry @valeriupredoi, I have not tried it yet. Could make sense as an alternative to Docker Hub, since that service is also more-and-more paid. Other than that I think we only/mostly publish using pip and Conda, and for both it does not seem to be an advantage (if even possible) to switch to GitHub.

**Comment by valeriupredoi** [comment]
good points and good reminder @nielsdrost - meant to close this a while ago when I had realized this is a completely different curry dish :+1:
