### ISSUE TITLE
How to use ERA-5 hourly data with ESMValTool

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#85]
For the [eWaterCycle](https://www.ewatercycle.org/) project we would like to use ERA-5 hourly data with ESMValTool. This would probably require a cmorization script, but I'm not sure which CMOR table to use. There is no hourly data in CMIP5 and CMIP6 has only the [E1hr](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_E1hr.json) mip table for hourly data. I guess we could extend that with custom variables, to get more ERA-5 data supported, but it looks like we would need to start a new 'project' for that. @mattiarighi any ideas on what would be the best way to proceed?

**Comment by mattiarighi** [comment]
There are two issues, CMOR tables and MIP in output file name.

CMOR tables for the same variable in two different mips have usually the same metadata (except for `comment`). So if a table is not available in the resolution of your data, you can use another one. We had a similar case when cmorizing [CERES-SYN1deg](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/utils/cmorizers/obs/cmorize_obs_CERES-SYN1deg.ncl), were the `Amon` tables were used also for `3hr` frequency, since not all variables were available in `3hr` tables.

Concerning the MIP in the file name, this is pretty much our choice. We can decide to define a `1hr` MIP for this dataset even if it is not an official one. It would only be used for file naming purposes.

@hb326 also has experience with this dataset.

PS: why is this issue in the core repository?

**Comment by bouweandela** [comment]
> PS: why is this issue in the core repository?

Because it's a question about how to make ESMValTool Core understand this data.

**Comment by bouweandela** [comment]
Thanks for the suggestion, I will try to get it working.

**Comment by bouweandela** [comment]
> We had a similar case when cmorizing CERES-SYN1deg, were the Amon tables were used also for 3hr frequency, since not all variables were available in 3hr tables.

This works because the OBS project is CMIP5 + custom tables and there is a 3hr table in CMIP5 which can be extended with custom entries, but there is no 1hr table, so nothing to add the custom variable to and therefore it will not work for hourly data. Shall I make an additional OBS project based on CMIP6, so I can extend that with custom variables?

**Comment by bouweandela** [comment]
Or shall I make an ERA5 project instead, and copy paste the relevant CMOR tables from CMIP6?

**Comment by bouweandela** [comment]
Created a draft pull request here https://github.com/ESMValGroup/ESMValCore/pull/111 and associated CMORizer here https://github.com/ESMValGroup/ESMValTool/pull/1167.

**Comment by mattiarighi** [comment]
I think an additional OBS project based on CMIP6 is better than creating an ERA5 project instead.

**Comment by bouweandela** [comment]
Any preference for a name? OBS6?

**Comment by mattiarighi** [comment]
:+1:
